<?php

function vimeoibby_field_schema($field) {
  $columns = array(
    'vimeo_id' => array('type' => 'varchar', 'length' => 10, 'not null' => FALSE),
    'vimeo_link' => array('type' => 'varchar', 'length' => 128, 'not null' => FALSE),
  );
  $indexes = array(
    'vimeo_id' => array('vimeo_id'),
    'vimeo_link' => array('vimeo_link'),
  );
  return array(
    'columns' => $columns,
    'indexes' => $indexes,
  );
}