<?php

/**
 * Implements hook_field_info().
 *
 * Provides the description of the field.
 */
function vimeoibby_field_info() {
  return array(
    'vimeo_ibby' => array(
      'label' => t('Vimeo video for ib.by'),
      'description' => t('Output vimeo video'),
      'default_widget' => 'vimeoibby_video',
      'default_formatter' => 'vimeoibby_formatter_link',
      'instance_settings' => array(
        'thumbnail_directory' => '',
      ),
    ),
  );
}

/**
 * Implements hook_field_is_empty().
 */
function vimeoibby_field_is_empty($item, $field) {
  return empty($item['vimeo_link']);
}

/**
 * Implements hook_field_instance_settings_form().
 */
function vimeoibby_field_instance_settings_form($field, $instance) {
  $settings = $instance['settings'];
  $form['thumbnail_directory'] = array(
    '#type' => 'textfield',
    '#title' => t('Thumbnail directory'),
    '#default_value' => $settings['thumbnail_directory'],
    '#description' => t('Optional subdirectory within the upload destination where thumbnail will be stored. Do not include preceding or trailing slashes.'),
    '#weight' => 3,
  );
  return $form;
}

/**
 * Implements hook_field_formatter_info().
 */
function vimeoibby_field_formatter_info() {
  $formatter = array(
    'vimeoibby_formatter_link' => array(
      'label' => t('Vimeo link'),
      'field types' => array('vimeo_ibby'),
    ),
    'vimeoibby_formatter_thumbnail' => array(
      'label' => t('Vimeo thumbnail'),
      'field types' => array('vimeo_ibby'),
      'settings' => vimeoibby_default_settings_thumbnail(),
      //todo засунуть файл в настройку
    ),
    'vimeoibby_formatter_video' => array(
      'label' => t('Vimeo video'),
      'field types' => array('vimeo_ibby'),
      'settings' => array('thumb_size' => '',)
    ),
  );
  return $formatter;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function vimeoibby_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $type = $instance['display'][$view_mode]['type'];
  $settings = $display['settings'];
  $image_styles = image_style_options(FALSE, PASS_THROUGH);
  switch ($type) {
    case'vimeoibby_formatter_thumbnail':
      $element['thumb_size'] = array(
        '#title' => t('Image style'),
        '#type' => 'select',
        '#default_value' => $settings['thumb_size'],
        '#empty_option' => t('None (original image)'),
        '#options' => $image_styles,
      );
      $link_types = array(
        'content' => t('Content'),
        'video' => t('Video'),
      );
      $element['image_link'] = array(
        '#title' => t('Link image to'),
        '#type' => 'select',
        '#default_value' => $settings['image_link'],
        '#empty_option' => t('Nothing'),
        '#options' => $link_types,
      );
      break;
  }
  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function vimeoibby_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $type = $instance['display'][$view_mode]['type'];
  $summary = array();

  $image_styles = image_style_options(FALSE, PASS_THROUGH);
  unset($image_styles['']);
  switch ($type) {
    case 'vimeoibby_formatter_thumbnail':
      if (isset($image_styles[$settings['thumb_size']])) {
        $summary[] = t('Image style: @style', array('@style' => $image_styles[$settings['thumb_size']]));
      }
      else {
        $summary[] = t('Original image');
      }
      $link_types = array(
        'content' => t('Linked to content'),
        'video' => t('Linked to video'),
      );
      if (isset($link_types[$settings['image_link']])) {
        $summary[] = $link_types[$settings['image_link']];
      }
      break;
  }

  return implode('<br />', $summary);
}

/**
 * Vimeo.com's default thumbnail settings.
 * @return Array
 *    Default values keyed by the setting name.
 */
function vimeoibby_default_settings_thumbnail() {
  $defaults = array(
    'thumb_size' => 'medium',
    'image_link' => '',
  );
  return $defaults;
}

/**
 * @param $vimeo_url - url on vimeo video
 * @return mixed
 */
function _vimeo_oembed($vimeo_url) {
  $oembed_url = url('http://vimeo.com/api/oembed.json', array(
    'query' => array(
      'url' => $vimeo_url,
    )
  ));
  $response = drupal_http_request($oembed_url);
  $data = drupal_json_decode($response->data);
  return $data;
}

/**
 * Implements hook_field_presave().
 */
function vimeoibby_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {
  $settings = $instance['settings'];
  foreach($items as $delta=>$item){
    $file_path = file_build_uri($settings['thumbnail_directory']);
    if (!file_prepare_directory($file_path, $options = FILE_MODIFY_PERMISSIONS)) {
      drupal_mkdir($file_path);
    }
    $video = _vimeo_oembed($item['vimeo_link']);
    $file = system_retrieve_file($video['thumbnail_url'], $file_path, FILE_EXISTS_REPLACE);
  }
}

/**
 * Implements hook_field_formatter_view().
 */
function vimeoibby_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, &$items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'vimeoibby_formatter_link':
      foreach ($items as $delta => $item) {
        $element[$delta]['#markup'] = '<p>' . l($item['vimeo_link'], $item['vimeo_link'], array('attributes' => array('target' => '_blank'))) . '</p>';
      }
      break;

    case 'vimeoibby_formatter_thumbnail':
      foreach ($items as $delta => $item) {
        $image_link = file_load($item['vimeo_thumb_fid'])->uri;
        $attributes = array(
          'html' => TRUE,
          'attributes' => array('target' => '_blank')
        );
        $image = theme('image_style', array('style_name' => $display['settings']['thumb_size'], 'path' => $image_link));
        $uri = entity_uri($entity_type, $entity);
        if ($display['settings']['image_link'] == 'content') {
          $content = l($image, $uri['path'], $attributes);
        }
        elseif ($display['settings']['image_link'] == 'video') {
          $content = l($image, $item['vimeo_link'], $attributes);
        }
        else {
          $content = $image;
        }

        $element[$delta]['#markup'] = '<p>' . $content . '</p>';
      }
      break;

    case 'vimeoibby_formatter_video':
      foreach ($items as $delta => $item) {
        $video = _vimeo_oembed($item['vimeo_link']);
        $element[$delta]['#markup'] = '<p>' . $video['html'] . '</p>';
      }
      break;
  }
  return $element;
}

/**
 * Implements hook_field_widget_info().
 */
function vimeoibby_field_widget_info() {
  return array(
    'vimeoibby_video' => array(
      'label' => t('Vimeo video'),
      'field types' => array('vimeo_ibby'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function vimeoibby_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $element += array(
    '#delta' => $delta,
    'vimeo_link' => array(),
    'vimeo_id' => array(),
    'vimeo_thumb_fid' => array(),
  );
  switch ($instance['widget']['type']) {
    case 'vimeoibby_video':
      $element['vimeo_link'] += array(
        '#title' => t('Link to Vimeo video'),
        '#type' => 'textfield',
        '#default_value' => isset($items[$delta]['vimeo_link']) ? $items[$delta]['vimeo_link'] : '',
        '#size' => 128,
        '#maxlength' => 128,
        '#delta' => $delta,
        '#field_name' => $element['#field_name'],
        '#language' => $element['#language'],
      );
      $element['vimeo_id'] += array(
        '#delta' => $delta,
        '#field_name' => $element['#field_name'],
        '#language' => $element['#language'],
        '#markup' => isset($items[$delta]['vimeo_link']) ? 'Vimeo video ID: ' . _vimeo_oembed($items[$delta]['vimeo_link'])['video_id'] : '',
        '#element_validate' => array('insert_vimeo_id'),
      );
      $element['vimeo_thumb_fid'] += array(
        '#delta' => $delta,
        '#field_name' => $element['#field_name'],
        '#language' => $element['#language'],
        '#element_validate' => array('insert_vimeo_thumb_fid'),
      );
      break;
  }
  return $element;
}


/**
 * Convert video link to video id
 */
function insert_vimeo_id($element, &$form_state) {
  $delta = $element['#delta'];
  $field = $form_state['field'][$element['#field_name']][$element['#language']]['field'];
  $field_name = $field['field_name'];
  if (isset($form_state['values'][$field_name][$element['#language']][$delta])) {
    $value = $form_state['values'][$field_name][$element['#language']][$delta];
    $vimeo_id = _vimeo_oembed($value['vimeo_link'])['video_id'];
    form_set_value($element, $vimeo_id, $form_state);
  }
}

/**
 * Save image
 */
function insert_vimeo_thumb_fid($element, &$form_state) {
  $delta = $element['#delta'];
  $file_path = file_build_uri($form_state['field'][$element['#field_name']][$element['#language']]['instance']['settings']['thumbnail_directory']);
  $vimeo_link = $form_state['values'][$element['#field_name']][$element['#language']][$delta]['vimeo_link'];
  $file = new stdClass();
  if (!file_prepare_directory($file_path, FILE_MODIFY_PERMISSIONS)) {
    drupal_mkdir($file_path);
  }
  $video = _vimeo_oembed($vimeo_link);
  $file = system_retrieve_file($video['thumbnail_url'], $file_path, TRUE, FILE_EXISTS_REPLACE);
  form_set_value($element, $file->fid, $form_state);
}
